// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: transport/grpc/gitspb/gits.proto

package gitspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *BookGetRequest) Reset() {
	*x = BookGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookGetRequest) ProtoMessage() {}

func (x *BookGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookGetRequest.ProtoReflect.Descriptor instead.
func (*BookGetRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{0}
}

func (x *BookGetRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BookAddRequest) Reset() {
	*x = BookAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAddRequest) ProtoMessage() {}

func (x *BookAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAddRequest.ProtoReflect.Descriptor instead.
func (*BookAddRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{1}
}

func (x *BookAddRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book   *Book  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	BookId string `protobuf:"bytes,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *BookUpdateRequest) Reset() {
	*x = BookUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdateRequest) ProtoMessage() {}

func (x *BookUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdateRequest.ProtoReflect.Descriptor instead.
func (*BookUpdateRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{2}
}

func (x *BookUpdateRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *BookUpdateRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *BookDeleteRequest) Reset() {
	*x = BookDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDeleteRequest) ProtoMessage() {}

func (x *BookDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDeleteRequest.ProtoReflect.Descriptor instead.
func (*BookDeleteRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{3}
}

func (x *BookDeleteRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BookGetResponse) Reset() {
	*x = BookGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookGetResponse) ProtoMessage() {}

func (x *BookGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookGetResponse.ProtoReflect.Descriptor instead.
func (*BookGetResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{4}
}

func (x *BookGetResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BookAddResponse) Reset() {
	*x = BookAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAddResponse) ProtoMessage() {}

func (x *BookAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAddResponse.ProtoReflect.Descriptor instead.
func (*BookAddResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{5}
}

func (x *BookAddResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BookUpdateResponse) Reset() {
	*x = BookUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdateResponse) ProtoMessage() {}

func (x *BookUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdateResponse.ProtoReflect.Descriptor instead.
func (*BookUpdateResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{6}
}

func (x *BookUpdateResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type BookDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BookDeleteResponse) Reset() {
	*x = BookDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDeleteResponse) ProtoMessage() {}

func (x *BookDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDeleteResponse.ProtoReflect.Descriptor instead.
func (*BookDeleteResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{7}
}

func (x *BookDeleteResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId      string `protobuf:"bytes,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthorId    string `protobuf:"bytes,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	PublisherId string `protobuf:"bytes,4,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{8}
}

func (x *Book) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Book) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

type AuthorGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *AuthorGetRequest) Reset() {
	*x = AuthorGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorGetRequest) ProtoMessage() {}

func (x *AuthorGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorGetRequest.ProtoReflect.Descriptor instead.
func (*AuthorGetRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorGetRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type AuthorAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *AuthorAddRequest) Reset() {
	*x = AuthorAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorAddRequest) ProtoMessage() {}

func (x *AuthorAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorAddRequest.ProtoReflect.Descriptor instead.
func (*AuthorAddRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{10}
}

func (x *AuthorAddRequest) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type AuthorUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author   *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	AuthorId string  `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *AuthorUpdateRequest) Reset() {
	*x = AuthorUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorUpdateRequest) ProtoMessage() {}

func (x *AuthorUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorUpdateRequest.ProtoReflect.Descriptor instead.
func (*AuthorUpdateRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{11}
}

func (x *AuthorUpdateRequest) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *AuthorUpdateRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type AuthorDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *AuthorDeleteRequest) Reset() {
	*x = AuthorDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorDeleteRequest) ProtoMessage() {}

func (x *AuthorDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorDeleteRequest.ProtoReflect.Descriptor instead.
func (*AuthorDeleteRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{12}
}

func (x *AuthorDeleteRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type AuthorGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *AuthorGetResponse) Reset() {
	*x = AuthorGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorGetResponse) ProtoMessage() {}

func (x *AuthorGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorGetResponse.ProtoReflect.Descriptor instead.
func (*AuthorGetResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{13}
}

func (x *AuthorGetResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type AuthorAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *AuthorAddResponse) Reset() {
	*x = AuthorAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorAddResponse) ProtoMessage() {}

func (x *AuthorAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorAddResponse.ProtoReflect.Descriptor instead.
func (*AuthorAddResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{14}
}

func (x *AuthorAddResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type AuthorUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AuthorUpdateResponse) Reset() {
	*x = AuthorUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorUpdateResponse) ProtoMessage() {}

func (x *AuthorUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorUpdateResponse.ProtoReflect.Descriptor instead.
func (*AuthorUpdateResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{15}
}

func (x *AuthorUpdateResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type AuthorDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AuthorDeleteResponse) Reset() {
	*x = AuthorDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorDeleteResponse) ProtoMessage() {}

func (x *AuthorDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorDeleteResponse.ProtoReflect.Descriptor instead.
func (*AuthorDeleteResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{16}
}

func (x *AuthorDeleteResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{17}
}

func (x *Author) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublisherGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublisherId string `protobuf:"bytes,1,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
}

func (x *PublisherGetRequest) Reset() {
	*x = PublisherGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherGetRequest) ProtoMessage() {}

func (x *PublisherGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherGetRequest.ProtoReflect.Descriptor instead.
func (*PublisherGetRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{18}
}

func (x *PublisherGetRequest) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

type PublisherAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher *Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *PublisherAddRequest) Reset() {
	*x = PublisherAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherAddRequest) ProtoMessage() {}

func (x *PublisherAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherAddRequest.ProtoReflect.Descriptor instead.
func (*PublisherAddRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{19}
}

func (x *PublisherAddRequest) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

type PublisherUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher   *Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublisherId string     `protobuf:"bytes,2,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
}

func (x *PublisherUpdateRequest) Reset() {
	*x = PublisherUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherUpdateRequest) ProtoMessage() {}

func (x *PublisherUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherUpdateRequest.ProtoReflect.Descriptor instead.
func (*PublisherUpdateRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{20}
}

func (x *PublisherUpdateRequest) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *PublisherUpdateRequest) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

type PublisherDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublisherId string `protobuf:"bytes,1,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
}

func (x *PublisherDeleteRequest) Reset() {
	*x = PublisherDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherDeleteRequest) ProtoMessage() {}

func (x *PublisherDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherDeleteRequest.ProtoReflect.Descriptor instead.
func (*PublisherDeleteRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{21}
}

func (x *PublisherDeleteRequest) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

type PublisherGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher *Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *PublisherGetResponse) Reset() {
	*x = PublisherGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherGetResponse) ProtoMessage() {}

func (x *PublisherGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherGetResponse.ProtoReflect.Descriptor instead.
func (*PublisherGetResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{22}
}

func (x *PublisherGetResponse) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

type PublisherAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher *Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *PublisherAddResponse) Reset() {
	*x = PublisherAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherAddResponse) ProtoMessage() {}

func (x *PublisherAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherAddResponse.ProtoReflect.Descriptor instead.
func (*PublisherAddResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{23}
}

func (x *PublisherAddResponse) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

type PublisherUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PublisherUpdateResponse) Reset() {
	*x = PublisherUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherUpdateResponse) ProtoMessage() {}

func (x *PublisherUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherUpdateResponse.ProtoReflect.Descriptor instead.
func (*PublisherUpdateResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{24}
}

func (x *PublisherUpdateResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type PublisherDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PublisherDeleteResponse) Reset() {
	*x = PublisherDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherDeleteResponse) ProtoMessage() {}

func (x *PublisherDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherDeleteResponse.ProtoReflect.Descriptor instead.
func (*PublisherDeleteResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{25}
}

func (x *PublisherDeleteResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Publisher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublisherId string `protobuf:"bytes,1,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_gitspb_gits_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_transport_grpc_gitspb_gits_proto_rawDescGZIP(), []int{26}
}

func (x *Publisher) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *Publisher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_transport_grpc_gitspb_gits_proto protoreflect.FileDescriptor

var file_transport_grpc_gitspb_gits_proto_rawDesc = []byte{
	0x0a, 0x20, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x69, 0x74, 0x73, 0x70, 0x62, 0x2f, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x69, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x4b, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f,
	0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x31,
	0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f,
	0x6b, 0x22, 0x31, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x2c, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x70, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x2e, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x22, 0x38, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x57, 0x0a, 0x13,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x2e,
	0x0a, 0x14, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2e,
	0x0a, 0x14, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x38,
	0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x69,
	0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x3a, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45,
	0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x69, 0x74, 0x73,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x17,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x31, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x41, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xc8, 0x06, 0x0a, 0x04, 0x47, 0x69, 0x74, 0x73, 0x12, 0x38,
	0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x47, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x69, 0x74, 0x73,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x64, 0x64, 0x12, 0x14, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x69, 0x74, 0x73,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x17, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x69, 0x74, 0x73,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67,
	0x69, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x41, 0x64, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x19, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67,
	0x69, 0x74, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x47, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x69, 0x74,
	0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x12, 0x19, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50,
	0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1d, 0x5a, 0x1b, 0x74, 0x65, 0x73, 0x74, 0x33, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x73, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_gitspb_gits_proto_rawDescOnce sync.Once
	file_transport_grpc_gitspb_gits_proto_rawDescData = file_transport_grpc_gitspb_gits_proto_rawDesc
)

func file_transport_grpc_gitspb_gits_proto_rawDescGZIP() []byte {
	file_transport_grpc_gitspb_gits_proto_rawDescOnce.Do(func() {
		file_transport_grpc_gitspb_gits_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_gitspb_gits_proto_rawDescData)
	})
	return file_transport_grpc_gitspb_gits_proto_rawDescData
}

var file_transport_grpc_gitspb_gits_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_transport_grpc_gitspb_gits_proto_goTypes = []interface{}{
	(*BookGetRequest)(nil),          // 0: gits.BookGetRequest
	(*BookAddRequest)(nil),          // 1: gits.BookAddRequest
	(*BookUpdateRequest)(nil),       // 2: gits.BookUpdateRequest
	(*BookDeleteRequest)(nil),       // 3: gits.BookDeleteRequest
	(*BookGetResponse)(nil),         // 4: gits.BookGetResponse
	(*BookAddResponse)(nil),         // 5: gits.BookAddResponse
	(*BookUpdateResponse)(nil),      // 6: gits.BookUpdateResponse
	(*BookDeleteResponse)(nil),      // 7: gits.BookDeleteResponse
	(*Book)(nil),                    // 8: gits.Book
	(*AuthorGetRequest)(nil),        // 9: gits.AuthorGetRequest
	(*AuthorAddRequest)(nil),        // 10: gits.AuthorAddRequest
	(*AuthorUpdateRequest)(nil),     // 11: gits.AuthorUpdateRequest
	(*AuthorDeleteRequest)(nil),     // 12: gits.AuthorDeleteRequest
	(*AuthorGetResponse)(nil),       // 13: gits.AuthorGetResponse
	(*AuthorAddResponse)(nil),       // 14: gits.AuthorAddResponse
	(*AuthorUpdateResponse)(nil),    // 15: gits.AuthorUpdateResponse
	(*AuthorDeleteResponse)(nil),    // 16: gits.AuthorDeleteResponse
	(*Author)(nil),                  // 17: gits.Author
	(*PublisherGetRequest)(nil),     // 18: gits.PublisherGetRequest
	(*PublisherAddRequest)(nil),     // 19: gits.PublisherAddRequest
	(*PublisherUpdateRequest)(nil),  // 20: gits.PublisherUpdateRequest
	(*PublisherDeleteRequest)(nil),  // 21: gits.PublisherDeleteRequest
	(*PublisherGetResponse)(nil),    // 22: gits.PublisherGetResponse
	(*PublisherAddResponse)(nil),    // 23: gits.PublisherAddResponse
	(*PublisherUpdateResponse)(nil), // 24: gits.PublisherUpdateResponse
	(*PublisherDeleteResponse)(nil), // 25: gits.PublisherDeleteResponse
	(*Publisher)(nil),               // 26: gits.Publisher
}
var file_transport_grpc_gitspb_gits_proto_depIdxs = []int32{
	8,  // 0: gits.BookAddRequest.book:type_name -> gits.Book
	8,  // 1: gits.BookUpdateRequest.book:type_name -> gits.Book
	8,  // 2: gits.BookGetResponse.book:type_name -> gits.Book
	8,  // 3: gits.BookAddResponse.book:type_name -> gits.Book
	17, // 4: gits.AuthorAddRequest.author:type_name -> gits.Author
	17, // 5: gits.AuthorUpdateRequest.author:type_name -> gits.Author
	17, // 6: gits.AuthorGetResponse.author:type_name -> gits.Author
	17, // 7: gits.AuthorAddResponse.author:type_name -> gits.Author
	26, // 8: gits.PublisherAddRequest.publisher:type_name -> gits.Publisher
	26, // 9: gits.PublisherUpdateRequest.publisher:type_name -> gits.Publisher
	26, // 10: gits.PublisherGetResponse.publisher:type_name -> gits.Publisher
	26, // 11: gits.PublisherAddResponse.publisher:type_name -> gits.Publisher
	0,  // 12: gits.Gits.BookGet:input_type -> gits.BookGetRequest
	1,  // 13: gits.Gits.BookAdd:input_type -> gits.BookAddRequest
	2,  // 14: gits.Gits.BookUpdate:input_type -> gits.BookUpdateRequest
	3,  // 15: gits.Gits.BookDelete:input_type -> gits.BookDeleteRequest
	9,  // 16: gits.Gits.AuthorGet:input_type -> gits.AuthorGetRequest
	10, // 17: gits.Gits.AuthorAdd:input_type -> gits.AuthorAddRequest
	11, // 18: gits.Gits.AuthorUpdate:input_type -> gits.AuthorUpdateRequest
	12, // 19: gits.Gits.AuthorDelete:input_type -> gits.AuthorDeleteRequest
	18, // 20: gits.Gits.PublisherGet:input_type -> gits.PublisherGetRequest
	19, // 21: gits.Gits.PublisherAdd:input_type -> gits.PublisherAddRequest
	20, // 22: gits.Gits.PublisherUpdate:input_type -> gits.PublisherUpdateRequest
	21, // 23: gits.Gits.PublisherDelete:input_type -> gits.PublisherDeleteRequest
	4,  // 24: gits.Gits.BookGet:output_type -> gits.BookGetResponse
	5,  // 25: gits.Gits.BookAdd:output_type -> gits.BookAddResponse
	6,  // 26: gits.Gits.BookUpdate:output_type -> gits.BookUpdateResponse
	7,  // 27: gits.Gits.BookDelete:output_type -> gits.BookDeleteResponse
	13, // 28: gits.Gits.AuthorGet:output_type -> gits.AuthorGetResponse
	14, // 29: gits.Gits.AuthorAdd:output_type -> gits.AuthorAddResponse
	15, // 30: gits.Gits.AuthorUpdate:output_type -> gits.AuthorUpdateResponse
	16, // 31: gits.Gits.AuthorDelete:output_type -> gits.AuthorDeleteResponse
	22, // 32: gits.Gits.PublisherGet:output_type -> gits.PublisherGetResponse
	23, // 33: gits.Gits.PublisherAdd:output_type -> gits.PublisherAddResponse
	24, // 34: gits.Gits.PublisherUpdate:output_type -> gits.PublisherUpdateResponse
	25, // 35: gits.Gits.PublisherDelete:output_type -> gits.PublisherDeleteResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_transport_grpc_gitspb_gits_proto_init() }
func file_transport_grpc_gitspb_gits_proto_init() {
	if File_transport_grpc_gitspb_gits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_gitspb_gits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_gitspb_gits_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Publisher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_gitspb_gits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_gitspb_gits_proto_goTypes,
		DependencyIndexes: file_transport_grpc_gitspb_gits_proto_depIdxs,
		MessageInfos:      file_transport_grpc_gitspb_gits_proto_msgTypes,
	}.Build()
	File_transport_grpc_gitspb_gits_proto = out.File
	file_transport_grpc_gitspb_gits_proto_rawDesc = nil
	file_transport_grpc_gitspb_gits_proto_goTypes = nil
	file_transport_grpc_gitspb_gits_proto_depIdxs = nil
}
